version: "3"
services:
  webapi1:
    build: 
      context: .
      dockerfile: webapi1.dockerfile
    image: sample/multitenancy/webapi1
    env_file: 
      - .env.webapi1
    ports:
      - 5004:5004

  webapp:
    build:
      context: .
      dockerfile: webapp.dockerfile
    image: sample/multitenancy/webapp
    env_file:
      - .env.webapp
    ports:
      - 5005:${ASPNETCORE_PORT}