version: "3"
services:
  webapi1:
    build: 
      context: .
      dockerfile: webapi1.dockerfile
    image: kaml/sample/multitenant/webapi1
    env_file: 
      - .env.webapi1
    ports:
      - 5001:5001

  # webapi2:
  #   build: 
  #     context: .
  #     dockerfile: webapi1.dockerfile
  #   image: kaml/sample/multitenant/webapi1
  #   env_file: 
  #     - .env.webapi2
  #   ports:
  #     - 5002:5002

  webapp:
    build:
      context: .
      dockerfile: webapp.dockerfile
    image: kaml/sample/multitenant/webapp
    env_file:
      - .env.webapp
    ports:
      - 5000:5000